// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0vzQMo0_KpKV61O7886j2RnHmrbcUaZU',
    appId: '1:191295749352:web:51ec5696b707b18b9add5d',
    messagingSenderId: '191295749352',
    projectId: 'lab-12-835ef',
    authDomain: 'lab-12-835ef.firebaseapp.com',
    storageBucket: 'lab-12-835ef.firebasestorage.app',
    measurementId: 'G-9TFS61QQZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu0KYPbuXPzzoZl9tAf661k7uWydCWddI',
    appId: '1:191295749352:android:9780398fa229efe69add5d',
    messagingSenderId: '191295749352',
    projectId: 'lab-12-835ef',
    storageBucket: 'lab-12-835ef.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0vzQMo0_KpKV61O7886j2RnHmrbcUaZU',
    appId: '1:191295749352:web:82acdf73cf815e369add5d',
    messagingSenderId: '191295749352',
    projectId: 'lab-12-835ef',
    authDomain: 'lab-12-835ef.firebaseapp.com',
    storageBucket: 'lab-12-835ef.firebasestorage.app',
    measurementId: 'G-BNLQ5S81X6',
  );
}
